### ISSUE TITLE
TypeError: Cannot read property 'findIndex' of null

### ISSUE THREAD

**Issue by shierro** [artoliukkonen/serverless-appsync-boilerplate#1]
Hi,

I tried to follow instructions on README, then i get this error when trying to create a new query

`sls create appsync`

type: query
name: listPosts
name of single unit: Post

this is the full trace:

```
TypeError: Cannot read property 'findIndex' of null
    at serverless.yamlParser.parse.then (/Users/macuser/Development/rb/trm/trm-backend-boilerplate/node_modules/serverless-appsync-jest-plugin/lib/create-resolver.js:200:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From previous event:
    at PluginManager.invoke (/Users/macuser/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:446:22)
    at PluginManager.run (/Users/macuser/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:477:17)
    at variables.populateService.then (/Users/macuser/.config/yarn/global/node_modules/serverless/lib/Serverless.js:110:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/Users/macuser/.config/yarn/global/node_modules/serverless/lib/Serverless.js:97:6)
    at serverless.init.then (/Users/macuser/.config/yarn/global/node_modules/serverless/bin/serverless:43:28)
    at /Users/macuser/.config/yarn/global/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/macuser/.config/yarn/global/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at initializeErrorReporter.then (/Users/macuser/.config/yarn/global/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at /Users/macuser/.config/yarn/global/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/Users/macuser/.config/yarn/global/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by artoliukkonen** [comment]
Sorry for late reply. For some reason I didn't get email notification from this.

Boilerplate here was using old version of jest plugin that contained a bug. I've now update this in package.json . You can either download this boilerplate again or just update the plugin manually.
